# Generated by Django 4.1.7 on 2023-02-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_email_alias_customgroup_picture_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='expiring_link_time',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='picture_size',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
