# Generated by Django 4.1.7 on 2023-02-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customgroup_expiring_link_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='expiring_link_time',
        ),
    ]
