# Generated by Django 4.1.7 on 2023-03-02 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uploaded', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('arbitrary_thumbnail_sizes', 'Will recive arbitrary thumbnail sizes'), ('Originally_uploaded_picture', 'presence of the link to the originally uploaded file'), ('Generate_expiring_links', 'Ability to generate expiring links with custom expiration time'), ('200px_thumbnail', 'Ability to generate 200px thumbnail'), ('400px_thumbnail', 'Ability to generate 400px thumbnail')],
            },
        ),
    ]
