# Generated by Django 4.1.7 on 2023-02-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picturesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'permissions': [('arbitrary thumbnail sizes', 'Will recive arbitrary thumbnail sizes'), ('Originally uploaded picture', 'presence of the link to the originally uploaded file'), ('Generate expiring links', 'Ability to generate expiring links with custom expiration time'), ('200px thumbnail', 'Ability to generate 200px thumbnail'), ('400px thumbnail', 'Ability to generate 400px thumbnail')]},
        ),
    ]
