# Generated by Django 4.1.7 on 2023-03-04 17:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picturesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='uploaded',
            field=models.ImageField(unique=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Expiringlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
                ('validuntil', models.TimeField()),
                ('duration', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(3000)])),
                ('linkto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picturesapp.picture', to_field='uploaded')),
            ],
        ),
    ]
