# Generated by Django 4.1.7 on 2023-02-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picturesapp', '0002_alter_picture_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default='picture1', max_length=30),
            preserve_default=False,
        ),
    ]
